# Usa uma versão simplificada do Java 17 para diminuir o tamanho final da imagem
FROM eclipse-temurin:17-jre-alpine

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o JAR gerado pela compilação local
COPY target/agcs-service-0.0.1-SNAPSHOT.jar app.jar

# Define o comando de execução
CMD ["java", "-jar", "app.jar"]

# Expõe a porta usada pela aplicação
EXPOSE 8086